baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
description = "An elegant, mobile-ready, minimalistic theme."
theme="one"
tags = ["pcom"]
publishDir = "docs"

[params]
    navigation = ["archives.md", "about.md"]

